module.exports = {
	pages:{
		user:{
			entry:"./src/pages/user/main.js",
			template:"./public/index.html",
			filename:"index.html"
		},
		manager:{
			entry:"./src/pages/manager/main.js",
			template:"./public/index.html",
			filename:"manager.html"
		},
		loginOrRegister:{
			entry:"./src/pages/loginOrRegister/main.js",
			template:"./public/index.html",
			filename:"login.html"
		},
	}
}